version: '3'
services:
  expensive:
    container_name: expensive
    build: .
    command: yarn run-exp
    environment: 
      - PORT=80
  optimize:
    container_name: optimize
    build: .
    command: yarn run-opt
    environment: 
      - PORT=80
  nginx:
    container_name: nginx
    image: nginx:1.19.0-alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 8087:80
    environment:
      - NGINX_HOST=nginx
      - NGINX_PORT=80
    links: 
      - optimize:optimize
      - expensive:expensive